apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: {{ .Values.ingressType }}
  ports:
    - protocol: TCP
    # expose service port to outside world
      port: 8081
    #  target port to connect to for mongo-web pod
      targetPort: 8081
    # open port on node 3000 to connect to from outside world
      nodePort: 30000